package com.martinsterentjevs.cacheit.integration.ws

import com.martinsterentjevs.cacheit.dtos.note.NoteDto
import com.martinsterentjevs.cacheit.dtos.websockets.WsNudgeType
import com.martinsterentjevs.cacheit.services.NoteService
import com.martinsterentjevs.cacheit.services.TokenService
import com.martinsterentjevs.cacheit.testdata.AuthTestHelper.registerAndLogin
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import java.time.Instant
import java.util.UUID
import java.util.concurrent.TimeoutException
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

class NoteNudgeTriggerIntegrationTest : WsIntegrationTestBase() {
    @Autowired
    lateinit var tokenService: TokenService

    @Autowired
    lateinit var noteService: NoteService

    private fun noteDto(
        userId: UUID,
        title: String = "t",
        body: String = "b"
    ) = NoteDto(
        noteId = UUID.randomUUID(),
        userId = userId,
        lastModifiedAt = Instant.now(),
        isDeleted = false,
        hasHistory = false,
        encTitle = title,
        encBody = body,
        encDrawing = null,
        lockedByDeviceId = null,
        lockedAt = null
    )

    @Test
    fun `updateNote triggers NOTE_UPDATED nudge after commit`() {
        val user = registerAndLogin(restTemplate, tokenService)
        val (_, received) =
            connectAndCaptureNudges(user.accessToken)

        val note =
            noteService.addNote(
                noteDto(user.userId),
                "Bearer ${user.accessToken}"
            )

        val mark = received.mark()

        val updated =
            noteService.updateNote(
                note.copy(encTitle = "enc-title-v2"),
                "Bearer ${user.accessToken}"
            )

        val nudge =
            received.awaitNudge(mark) {
                it.type == WsNudgeType.NOTE_UPDATED &&
                    it.noteId == updated.noteId
            }

        assertEquals(WsNudgeType.NOTE_UPDATED, nudge.type)
        assertEquals(updated.noteId, nudge.noteId)
    }

    @Test
    fun `deleteNote triggers NOTE_DELETED nudge after commit`() {
        val user = registerAndLogin(restTemplate, tokenService)
        val (_, received) =
            connectAndCaptureNudges(user.accessToken)

        val note =
            noteService.addNote(
                noteDto(user.userId),
                "Bearer ${user.accessToken}"
            )

        val mark = received.mark()

        noteService.deleteNote(
            note.noteId,
            "Bearer ${user.accessToken}"
        )

        val nudge =
            received.awaitNudge(mark) {
                it.type == WsNudgeType.NOTE_DELETED &&
                    it.noteId == note.noteId
            }

        assertEquals(WsNudgeType.NOTE_DELETED, nudge.type)
        assertEquals(note.noteId, nudge.noteId)
    }

    @Test
    fun `acquireDrawingLock triggers NOTE_LOCK_ACQUIRED nudge with correct device id`() {
        val user = registerAndLogin(restTemplate, tokenService)
        val (_, received) =
            connectAndCaptureNudges(user.accessToken)

        val note =
            noteService.addNote(
                noteDto(user.userId),
                "Bearer ${user.accessToken}"
            )

        val mark = received.mark()

        noteService.acquireDrawingLock(
            note.noteId,
            "Bearer ${user.accessToken}"
        )

        val nudge =
            received.awaitNudge(mark) {
                it.type == WsNudgeType.NOTE_LOCK_ACQUIRED &&
                    it.noteId == note.noteId
            }

        assertEquals(WsNudgeType.NOTE_LOCK_ACQUIRED, nudge.type)
        assertEquals(user.deviceId, nudge.lockedByDeviceId)
    }

    @Test
    fun `restoreVersion triggers NOTE_RESTORED nudge after commit`() {
        val user = registerAndLogin(restTemplate, tokenService)
        val (_, received) =
            connectAndCaptureNudges(user.accessToken)

        val note =
            noteService.addNote(
                noteDto(
                    user.userId,
                    title = "v1"
                ),
                "Bearer ${user.accessToken}"
            )

        val versions =
            noteService.getVersionHistory(
                note.noteId,
                "Bearer ${user.accessToken}"
            )

        val originalVersionId =
            versions.first().versionId

        noteService.updateNote(
            note.copy(encTitle = "v2"),
            "Bearer ${user.accessToken}"
        )

        /*
         * Mark the point after all setup operations.
         *
         * Any NOTE_UPDATED nudges generated by setup are irrelevant.
         * We do not clear the list because an earlier WebSocket delivery
         * could still be in flight.
         */
        val mark = received.mark()

        noteService.restoreVersion(
            note.noteId,
            originalVersionId,
            "Bearer ${user.accessToken}"
        )

        val nudge =
            received.awaitNudge(mark) {
                it.type == WsNudgeType.NOTE_RESTORED &&
                    it.noteId == note.noteId
            }

        assertEquals(WsNudgeType.NOTE_RESTORED, nudge.type)
        assertEquals(note.noteId, nudge.noteId)
    }

    @Test
    fun `releaseDrawingLock triggers NOTE_LOCK_RELEASED nudge after commit`() {
        val user = registerAndLogin(restTemplate, tokenService)
        val (_, received) =
            connectAndCaptureNudges(user.accessToken)

        val note =
            noteService.addNote(
                noteDto(user.userId),
                "Bearer ${user.accessToken}"
            )

        noteService.acquireDrawingLock(
            note.noteId,
            "Bearer ${user.accessToken}"
        )

        val mark = received.mark()

        noteService.releaseDrawingLock(
            note.noteId,
            "Bearer ${user.accessToken}"
        )

        val nudge =
            received.awaitNudge(mark) {
                it.type == WsNudgeType.NOTE_LOCK_RELEASED &&
                    it.noteId == note.noteId
            }

        assertEquals(WsNudgeType.NOTE_LOCK_RELEASED, nudge.type)
        assertEquals(note.noteId, nudge.noteId)
    }

    @Test
    fun `getNotes does not trigger a nudge`() {
        val user = registerAndLogin(restTemplate, tokenService)
        val (_, received) =
            connectAndCaptureNudges(user.accessToken)

        val note =
            noteService.addNote(
                noteDto(user.userId),
                "Bearer ${user.accessToken}"
            )

        /*
         * addNote does not have an event listener-backed nudge assertion
         * here, so establish the boundary immediately before getNotes().
         */
        val mark = received.mark()

        noteService.getNotes(
            "Bearer ${user.accessToken}"
        )

        val deadline =
            System.nanoTime() +
                java.util.concurrent.TimeUnit.SECONDS
                    .toNanos(2)

        while (System.nanoTime() < deadline) {
            val unexpected =
                received
                    .snapshot()
                    .drop(mark)
                    .firstOrNull()

            if (unexpected != null) {
                throw AssertionError(
                    "getNotes produced an unexpected nudge: $unexpected"
                )
            }

            Thread.sleep(10)
        }

        // Keep the note variable meaningful as setup verification.
        assertEquals(note.userId, user.userId)
    }

    @Test
    fun `nudge for one user is never delivered to another users session`() {
        val userA = registerAndLogin(restTemplate, tokenService)
        val userB = registerAndLogin(restTemplate, tokenService)

        val (_, receivedA) =
            connectAndCaptureNudges(userA.accessToken)

        val (_, receivedB) =
            connectAndCaptureNudges(userB.accessToken)

        val noteA =
            noteService.addNote(
                noteDto(userA.userId, title = "a"),
                "Bearer ${userA.accessToken}"
            )

        val markA = receivedA.mark()
        val markB = receivedB.mark()

        noteService.updateNote(
            noteA.copy(encTitle = "a2"),
            "Bearer ${userA.accessToken}"
        )

        val nudgeA =
            receivedA.awaitNudge(markA) {
                it.type == WsNudgeType.NOTE_UPDATED &&
                    it.noteId == noteA.noteId
            }

        assertEquals(noteA.noteId, nudgeA.noteId)

        /*
         * B has its own capture. Nothing generated for A should appear
         * after B's boundary.
         */
        assertFailsWith<TimeoutException> {
            receivedB.awaitNudge(markB) {
                it.type == WsNudgeType.NOTE_UPDATED &&
                    it.noteId == noteA.noteId
            }
        }
    }
}